### PR TITLE
feat: setup wordpress instance

### PR DESCRIPTION
**Pull request by KrawczowaKris**
# Summary
## AWS task
**Setup Wordpress instance**
- Use Amazon Linux 2023 AMI
- Setup nginx/php/php-fpm
- Use RDS for your MySQL host
- Setup wordpress with ALB loadbalancing with ACM SSL cert
- Setup Route53 domain YOURNAME-wordpress.saritasa-camps.link pointing to your ALB endpoint
- Setup AWS EFS that will:
  - host Wordpress plugins
  - host Wordpress images
- Install plugin https://wordpress.org/plugins/nextgen-gallery/
- Create a simple page using this plugin in the wordpress admin CMS and upload some test images
- Your EFS mount should tolerate instance restarts

hint: Your wordpress should work on both EC2 instances you have at this point. So when you're done with configuration - simply make AMI and start 2nd EC2 instance from that AMI.
- When you open PR: just include CLI commands that will prove the implementation.
- Link to your wordpress installation (that page with nextgen-gallery post)

## my results
https://nadezhda-niukina-user-wordpress-v2.saritasa-camps.link/index.php/2023/05/18/greate-people/

### CODE REVIEW

**Review by dmitry-mightydevops — CHANGES_REQUESTED** [review]
1. Your public instances should not allow public access over port 80
http://18.191.116.59/index.php/greate-people/
http://18.117.165.22/index.php/greate-people/

the access should be only allowed via ALB. 

2. Access over port 80 (http) should not be allowed for WP over ALB
http://nadezhda-niukina-user-lb-site-1658621625.us-east-2.elb.amazonaws.com/
or
http://nadezhda-niukina-user-site.saritasa-camps.link/index.php/greate-people/

show me prof via CLI calls that

a. Plugins
b. Content 

are stored in the EFS mounted on both EC2 instances.

**Comment by KrawczowaKris** [comment]
> 1. Your public instances should not allow public access over port 80
>        http://18.191.116.59/index.php/greate-people/
>        http://18.117.165.22/index.php/greate-people/
> 
> 
> the access should be only allowed via ALB.
> 
>     2. Access over port 80 (http) should not be allowed for WP over ALB
>        http://nadezhda-niukina-user-lb-site-1658621625.us-east-2.elb.amazonaws.com/
>        or
>        http://nadezhda-niukina-user-site.saritasa-camps.link/index.php/greate-people/
> 
> 
> show me prof via CLI calls that
> 
> a. Plugins b. Content
> 
> are stored in the EFS mounted on both EC2 instances.

**Comment by KrawczowaKris** [comment]
It turned out to close port 80 for ALB, but it is not possible to close access to ec2.

EFS on first ec2:
изображение
изображение
EFS on second ec2:
изображение
изображение

**Comment by dmitry-mightydevops** [comment]
> It turned out to close port 80 for ALB, but it is not possible to close access to ec2.

you still need to close the access to instances via port 80, to do that you will need:
a. Close via security groups associated with EC2 instances, **and**
b. Close listening on port 80

> 
> EFS on first ec2: изображение изображение EFS on second ec2: изображение изображение

these screenshots don't prove the location is EFS. You need to show the disk and the mount mapping at the OS level
- so you will need to show that full path to that folder where you exectuted the `ls`
- then you will need to show devices via `df -h`
- then you will need to show /etc/fstab  config

**Review by dmitry-mightydevops — CHANGES_REQUESTED** [review]
See above

**Comment by dmitry-mightydevops** [comment]
ok thanks for efs screenshots. Pls fix port 80 issue.

**Comment by KrawczowaKris** [comment]
changed everything, it seems to be working now

**Review by dmitry-mightydevops — CHANGES_REQUESTED** [review]
that is not correct implementation :) although the end result is what I expect.

image

- your ec2 instances should open port 80
- your SSL termination should happen in the ALB (i.e. user comes to your ALB over https, but then after ALB to EC2 the traffic should go in the HTTP == unencrypted, as the SSL was terminated in the ALB)
- to prevent other people reaching your site over port 80, you should add SG of your ALB instance in the source for the SG associated with your EC2 instances: https://us-east-2.console.aws.amazon.com/ec2/home?region=us-east-2#SecurityGroup:securityGroupId=sg-005404501b7414078

right now that security group has the following:

image

right now they listen on port 443

```
✗  nmap -sT 18.222.106.93
Starting Nmap 7.93 ( https://nmap.org ) at 2023-05-23 18:07 CDT
Nmap scan report for ec2-18-222-106-93.us-east-2.compute.amazonaws.com (18.222.106.93)
Host is up (0.13s latency).
Not shown: 998 filtered tcp ports (no-response)
PORT    STATE SERVICE
22/tcp  open  ssh
443/tcp open  https

Nmap done: 1 IP address (1 host up) scanned in 9.73 seconds

➜ nmap -sT 3.137.173.122              
Starting Nmap 7.93 ( https://nmap.org ) at 2023-05-23 18:08 CDT
Nmap scan report for ec2-3-137-173-122.us-east-2.compute.amazonaws.com (3.137.173.122)
Host is up (0.13s latency).
Not shown: 998 filtered tcp ports (no-response)
PORT    STATE SERVICE
22/tcp  open  ssh
443/tcp open  https

Nmap done: 1 IP address (1 host up) scanned in 9.54 seconds

```

however when I scan the ports - I should see no 80 no https. That would be the solution I expect where ALB goes into your EC2 instances by load-balancing over L4 HTTP protocol.

at the same time port 80, 443 are closed to the world if I scan outside the internal network. 

So make ALB SG to be the source of your EC2 associated SG on the port 80.

If something is not clear - ping me to discuss more

**Comment by KrawczowaKris** [comment]
изображение
remade it

**Review by dmitry-mightydevops — APPROVED** [review]
# good job

The implementation is correct

**Pull request merged**
